name: flutter_app_rename
description: A simple flutter app rename tool
version: 1.0.0
homepage: https://github.com/ivine/flutter_app_rename
repository: https://github.com/ivine/flutter_app_rename
documentation: https://github.com/ivine/flutter_app_rename
issue_tracker: https://github.com/ivine/flutter_app_rename/issues

environment:
  sdk: ^3.3.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  args: ^2.5.0
  xml: ^6.5.0
  path: ^1.9.0
  yaml: ^3.1.2
  yaml_edit: ^2.2.1
  xcode_parser1: ^1.2.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
